### ISSUE TITLE
Duplicate state action pairs in same batch yield different TD errors.

### ISSUE THREAD

**Issue by josephmaa** [ldoshi/rome-wasnt-built-in-a-day#212]
While running sibyl, loading batches after runs hit the error `ValueError: Metric values don't match for batch_idx duplicate. Current is 3.7595291137695312 and received 3.759540557861328 for batch idx: 3332.`. State action pairs are returning different values. 

This shouldn't be the case, the model should return the same td error for the same state action pair per batch. Lyric hits the assertion error on different step numbers from me, so there's also something up with the determinism of the model. Unknown if related. 

Suspecting code written in object_log_readers.py:
```if not math.isclose(duplicate_value, metric_value, abs_tol=1e-5):
                raise ValueError(
                    "Metric values don't match for batch_idx duplicate. Current "
                    f"is {duplicate_value} and received {metric_value} for batch idx: {batch_idx}."```

**Comment by ldoshi** [comment]
Address by increasing the threshold of whether floats are considered duplicates (ie more relaxed at 1e-4 instead of 1e-5)
